name: chama_app
description: "Um novo projeto Flutter para o Coral."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  firebase_core: ^2.27.0 # Versão atual (verifique a mais recente em pub.dev)
  cloud_firestore: ^4.15.7 # Versão atual
  firebase_storage: ^11.6.8 # Versão atual
  audioplayers: ^5.2.1 # Versão atual
  audio_service: ^0.18.12
  just_audio: ^0.9.36
  rxdart: ^0.27.7
  flutter_cache_manager: ^3.3.2
  share_plus: ^9.0.0
  table_calendar: ^3.1.2
  intl: ^0.19.0
  add_2_calendar: ^3.0.1
  flutter_pdfview: ^1.3.2
  cached_network_image: ^3.3.1
  smooth_page_indicator: ^1.1.0
  flutter_tts: ^4.0.2
  url_launcher: ^6.3.0
  provider: ^6.1.2
  carousel_slider: ^5.1.1
  screenshot: ^2.1.0
  path_provider: ^2.1.3
  firebase_messaging: ^14.7.10
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

 
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/nao_se_apague.png
    - assets/images/wallpaper.png
    - assets/images/wallpaper_light.png
    - assets/images/chama_coral.png
    - assets/images/template_partilha.png
    - assets/images/letras.svg
    - assets/images/banda.svg
    - assets/images/partitura.svg
    - assets/images/cifra.svg
    - assets/images/oracao.svg
    - assets/images/novo_usuario.svg
    - assets/images/agenda.svg
    - assets/images/kits_de_voz.svg
    - assets/images/recado.svg
    - assets/images/instagram.svg
    - assets/images/deezer.svg
    - assets/images/youtube.svg
    - assets/images/facebook.svg
    - assets/images/spotify.svg
    - assets/images/apple_music.svg
    - assets/images/youtube_music.svg
    - assets/images/chama_coral4.svg
    - assets/images/capa_light.svg
    - assets/fonts/
    - assets/sounds/
    - assets/sounds/metronome_tick.wav
    - assets/icon/
    - assets/icon/icon.png
    - assets/icon/icon2.png
    - assets/icon/icon3.png
    
  
  fonts:
    - family: Nexa
      fonts:
        - asset: assets/fonts/nexa1.ttf


        # Adicione esta seção no final do arquivo
flutter_native_splash:
  color: "#000000"
  image: assets/icon/icon3.png
  android_gravity: center
  ios_content_mode: center
  android: true
  ios: true
  android_12:
    color: "#000000"
    image: assets/icon/icon3.png
    icon_background_color: "#000000"
    branding: "assets/icon/logo_baixo.png"