name: chama_app
description: "Um novo projeto Flutter para o Coral."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  firebase_core: ^2.27.0 # Vers達o atual (verifique a mais recente em pub.dev)
  cloud_firestore: ^4.15.7 # Vers達o atual
  firebase_storage: ^11.6.8 # Vers達o atual
  audioplayers: ^5.2.1 # Vers達o atual
  audio_service: ^0.18.12
  just_audio: ^0.9.36
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/nao_se_apague.png
    - assets/images/wallpaper.png
    - assets/images/chama_coral.png
    - assets/images/letras.svg
    - assets/images/banda.svg
    - assets/images/partitura.svg
    - assets/images/cifra.svg
    - assets/images/oracao.svg
    - assets/images/novo_usuario.svg
    - assets/images/agenda.svg
    - assets/images/kits_de_voz.svg
    - assets/images/recado.svg
    - assets/fonts/

  fonts:
    - family: Nexa
      fonts:
        - asset: assets/fonts/nexa1.ttf