// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGAJC8kLAwyp4TbLH7UlinzFqf0p7fres',
    appId: '1:252469634828:web:c42f7253bcc6dbce788b29',
    messagingSenderId: '252469634828',
    projectId: 'chama-coral-277e8',
    authDomain: 'chama-coral-277e8.firebaseapp.com',
    storageBucket: 'chama-coral-277e8.firebasestorage.app',
    measurementId: 'G-FVL8JK6V3S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDid1XSQ-oJuF4ifK2kPnhAuy32YyhatjQ',
    appId: '1:252469634828:android:ab420a1133052026788b29',
    messagingSenderId: '252469634828',
    projectId: 'chama-coral-277e8',
    storageBucket: 'chama-coral-277e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBhcU7QSwUid4RgW8JbrmprPEqXVXVsSg',
    appId: '1:252469634828:ios:0c7404096333605d788b29',
    messagingSenderId: '252469634828',
    projectId: 'chama-coral-277e8',
    storageBucket: 'chama-coral-277e8.firebasestorage.app',
    iosBundleId: 'com.example.chamaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBhcU7QSwUid4RgW8JbrmprPEqXVXVsSg',
    appId: '1:252469634828:ios:0c7404096333605d788b29',
    messagingSenderId: '252469634828',
    projectId: 'chama-coral-277e8',
    storageBucket: 'chama-coral-277e8.firebasestorage.app',
    iosBundleId: 'com.example.chamaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGAJC8kLAwyp4TbLH7UlinzFqf0p7fres',
    appId: '1:252469634828:web:e3513cbd1e5a8bd9788b29',
    messagingSenderId: '252469634828',
    projectId: 'chama-coral-277e8',
    authDomain: 'chama-coral-277e8.firebaseapp.com',
    storageBucket: 'chama-coral-277e8.firebasestorage.app',
    measurementId: 'G-S9KD2NXH9V',
  );
}
